version: "3.9"

services:
  db:
    image: postgres:16
    container_name: flyblue_db
    restart: always
    environment:
      POSTGRES_USER: flyblue_user
      POSTGRES_PASSWORD: flyblue_pass
      POSTGRES_DB: flyblue_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: flyblue_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
